projmanagement/projmanagement/projects/urls.py
'''
Created on 03/12/2011

@author: eduardo
'''
from django.conf.urls.defaults import url, patterns
from django.views.generic import DetailView
from projmanagement.projects.models import Project
from projmanagement.projects.views import ProjectListView

urlpatterns = patterns('',
    # Examples:
    url(r'^$',
        ProjectListView.as_view(
                         queryset=Project.objects.all(),
                         context_object_name='project_list',
                         template_name='projects/projects.html')), 
    url(r'^(?P<pk>\d+)/$', 
        DetailView.as_view(
                           model=Project,
                           template_name='projects/tasks.html')),                     
    ### AJAX URLS ###
    url(r'^update/$', 'projects.views.update_project', name='update_project'),                                            
)

projmanagement/projmanagement/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.defaults import patterns, include, url

# To enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^js/([\w\.\-]+)/([\w\.\-]+)/$', 'views.javascript', name='javascript'),                       
    url(r'^projects/', include('projects.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

projmanagement/projmanagement/projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
	STATUS_CHOICES = (
		('N' , 'Not Started'),
		('S' , 'Started'),
		('F' , 'Finished'),
	)	
	codeName = models.CharField(max_length = 50)
	name = models.CharField(max_length = 200)
	status = models.CharField(max_length = 1, choices=STATUS_CHOICES, default='N')
	initDate = models.DateField(null=True, blank=True)
	dateToFinish = models.DateField(null=True, blank=True)
	comments = models.CharField(max_length = 300, blank=True)
	
	def __unicode__(self):
		return self.codeName + ' - ' + self.name

class Phase(models.Model):
	STATUS_CHOICES = (
		('N' , 'Not Started'),
		('S' , 'Started'),
		('F' , 'Finished'),
	)	
	phaseNumber = models.IntegerField()
	name = models.CharField(max_length = 200)
	project = models.ForeignKey(Project)
	isUnique = models.BooleanField()
	initDate = models.DateField(null=True, blank=True)
	status = models.CharField(max_length = 1, choices=STATUS_CHOICES, default='N')
	comments = models.CharField(max_length = 300, blank=True)

	def __unicode__(self):
		return str(self.phaseNumber) + ' - ' + self.name	
	
class Task(models.Model):
	STATUS_CHOICES = (
		('N' , 'Not Started'),
		('S' , 'Started'),
		('F' , 'Finished'),
		('ST', 'Stalled'),
	)	
	TASK_TYPES = (
		('PS', 'Proposal'),
		('PL', 'Planning'),
		('MG', 'Management'),
		('A', 'Analysis'),
		('TD', 'Technic Design'),
		('PG', 'Programming'),
		('T', 'Testing'),
		('PP', 'Preparing for production'),
		('IO', 'IOP'),
	)
	name = models.CharField(max_length=200)
	taskType = models.CharField(max_length=2, choices=TASK_TYPES, blank=True)
	phase = models.ForeignKey(Phase) 
	order = models.IntegerField(null=True, blank=True)
	level = models.IntegerField(default=1)
	superTask = models.ForeignKey('self',null=True, blank=True)
	predecessor = models.ManyToManyField('self', null=True, blank=True)
	successor = models.ManyToManyField('self', null=True, blank=True)
	estimateCost = models.IntegerField(null=True, blank=True)
	estimateInitDate = models.DateField(null=True, blank=True)
	EstimateEndDate = models.DateField(null=True, blank=True)
	realInitDate = models.DateField(null=True, blank=True)
	realEndDate = models.DateField(null=True, blank=True)
	realCost = models.IntegerField(null=True, blank=True)
	status = models.CharField(max_length = 2, choices=STATUS_CHOICES, default='N')
	comments = models.CharField(max_length = 300, blank=True)	

	def __unicode__(self):
		return self.name	

class Team(models.Model):
	name = models.CharField(max_length=200)
	surname1 = models.CharField(max_length=200, null=True, blank=True)
	surname2 = models.CharField(max_length=200, null=True, blank=True)
	TSOUsername = models.CharField(max_length=10, null=True, blank=True)
	IMSusername = models.CharField(max_length=10, null=True, blank=True)
	tasks = models.ManyToManyField(Task, through='Assignment', null=True, blank=True)

	def __unicode__(self):
		return self.name + ' ' + self.surname1	
	
class Assignment(models.Model):
	responsible = models.ForeignKey(Team)
	task = models.ForeignKey(Task)
	assignedCost = models.IntegerField(null=True, blank=True)
	compromiseDate = models.DateField(null=True, blank=True)
	comments = models.CharField(max_length = 300, blank=True)		

	def __unicode__(self):
		return self.esponsible.name + ' - ' + self.task.name	
	
class WorkReport(models.Model):
	assignment = models.ForeignKey(Assignment)
	dayReport = models.DateField()
	timeReport = models.IntegerField()
	

projmanagement/projmanagement/projects/forms.py
'''
Created on 15/12/2011

@author: Educalat
'''
from django.forms import ModelForm
from projmanagement.projects.models import Project

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        
        

projmanagement/projmanagement/projects/views.py
from django.core import serializers
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from projmanagement.projects.forms import ProjectForm
from projmanagement.projects.models import Project


class ProjectListView(ListView):

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        pr = Project.objects.get(pk=1)
        context['form'] = ProjectForm(instance=pr)
        context['project'] = pr 
        
        return context

def update_project(request):
    """
    AJAX client sends a serialized form by POST. ID comes from the article_id key.
    
    The function returns JSON, either the updated Article object, or the form's
    error dict.
    """
    try:
        project_id = int(request.POST['project_id'])
    except KeyError:
        raise Http404
    project = get_object_or_404(Project, id=project_id)
    form = ProjectForm(request.POST, instance=project)
    if form.is_valid():
        form.save()
        return HttpResponse(serializers.serialize('json', (project,)), mimetype="application/json")
    else:
        return HttpResponse(serializers.serialize('json', form.errors), mimetype="application/json")

projmanagement/projmanagement/views.py
'''
Created on 15/12/2011

@author: Educalat
'''
from django.shortcuts import render_to_response
from django.template import RequestContext

def javascript(request, app, js):
    """
    Used to request javascript templates.
    """
    return render_to_response("%s/%s.js" % (app, js),
        context_instance=RequestContext(request))

projmanagement/projmanagement/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es_ES" lang="es_ES">
<head>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>
{% block js %}{% endblock %}{# Override for view-specific js libraries to be loaded #}
<script type="text/javascript">
//<![CDATA[
{# Override this block to add functions to bind on document ready. #}
$(document).ready(function() {
    {% block docreadyjs %}{% endblock %}
});
{# Override this block to add inline js #}
{% block inlinejs %}{% endblock %}
//]]>
</script>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

projmanagement/projmanagement/templates/projects/project_form.html
<table>
    {{ form.as_table }}
</table>
<div id="feedback"></div>
<div><input type="button" name="save_button" id="save_button" value="Save" /></div>
<input type="hidden" name="project_id" id="project_id" value="{{ project.id }}" />

projmanagement/projmanagement/templates/projects/projects.html
{% extends "base.html" %}

{% block js %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui.js"></script>
<!--     <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.confirm_dialog.js"></script> -->
<!--     <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.message_box.js"></script> -->
<!--     <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.blockUI.js"></script> -->
    <script type="text/javascript" src="{% url javascript 'projects' 'projects' %}"></script>

{% endblock %}

{% block content %}

{% if project_list %}
    <ul>
    {% for project in project_list %}
        <li><a href="/projects/{{ project.id }}/">{{ project.codeName }} - {{ project.name}} </a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No projects are available.</p>
{% endif %}

<form id="project_form">{% csrf_token %}
{% include 'projects/project_form.html' %}
</form>

{% endblock %}

projmanagement/projmanagement/templates/projects/tasks.html
    <table border=1>
    <caption>Tareas del proyecto {{ project.codeName }} - {{ project.name }}</caption>
    <thead>
    <tr>
      <th rowspan="2">Tarea</th><th rowspan="2">Tipo</th><th rowspan="2">Valoración</th><th colspan="2">Fecha Inicio</th>
      <th colspan="2">Fecha Fin</th><th rowspan="2">Estado</th><th rowspan="2">Comentarios</th>      
    </tr>
    <tr>
    <th>Prevista</th><th>Real</th><th>Prevista</th><th>Real</th>
    </tr>
    </thead>
    <tbody>
    {% for phase in project.phase_set.all %}
    <tr><td colspawn="9"><b>{{ phase.name }}</b></td></tr>
      {% for task in phase.task_set.all %}
    	<tr>
        <td>{{ task.name }}</td>
        <td>{{ task.get_taskType_display|default:" " }}</td>
        <td>{{ task.estimateCost|default:" " }}</td>
        <td>{{ task.estimateInitDate|default:" " }}</td>
        <td>{{ task.realInitDate|default:" " }}</td>
        <td>{{ task.estimateEndDate|default:" " }}</td>
        <td>{{ task.realEndDate|default:" " }}</td>
        <td>{{ task.get_status_display|default:" " }}</td>
        <td>{{ task.comments|default:" " }}</td>
        </tr>
      {% endfor %}
    {% endfor %}
    </tbody>
    </table>    